FROM ubuntu

RUN apt-get update
RUN apt-get dist-upgrade -y

RUN apt-get install -y software-properties-common

RUN add-apt-repository ppa:webupd8team/java -y
RUN apt-get update
RUN apt-get install -y oracle-java8-installer
RUN apt-get clean

# Install maven
RUN apt-get install -y maven

WORKDIR /code

# Prepare by downloading dependencies
ADD pom.xml /code/pom.xml
RUN ["mvn", "dependency:resolve"]
RUN ["mvn", "verify"]

# Adding source, compile and package into a fat jar
ADD src /code/src
RUN ["mvn", "package"]

EXPOSE 8080
#CMD ["/usr/lib/jvm/java-8-openjdk-amd64/bin/java", "-jar", "target/resttest-0.0.1-SNAPSHOT.jar.jar"]

#RUN sh -c 'touch /app.jar'
# Prepare by downloading dependencies
#ADD pom.xml /pom.xml
#RUN ["mvn", "dependency:resolve"]
#RUN ["mvn", "verify"]
ENV JAVA_OPTS=""
ENTRYPOINT [ "sh", "-c", "java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar target/resttest-0.0.1-SNAPSHOT.jar" ]